posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #Buscar
    path('search/', views.search, name='search'),

    #Guardados
    path('add-to-saved/<int:product_id>/', views.add_to_saved, name='add-to-saved'),
    path('remove-from-saved/<str:product_id>/', views.remove_from_saved, name='remove-from-saved'),
    path('saved/', views.saved_view, name='saved-view'),

    #Filtrar
    path('filter-products/', views.filter_products, name="filter-product"),

    #Ordenar
    path('order-products/', views.order_products, name="order-product"),

    #Diferentes filtros
    path('<slug:slug>/', views.category_detail, name='category-detail'),
    path('<slug:category_slug>/<slug:slug>', views.subcategory_detail, name='subcategory-detail'),
    path('tag/<slug:slug>/', views.tagged, name='tagged'),

    #Detalles de la publicación
    path('<slug:category_slug>/<slug:subcategory_slug>/<slug:slug>/', views.product_detail, name='product-detail'),

    #Reseña
    path('add-review/<int:product_id>/', views.add_review, name='add-review'),
]

prueba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import frontpage, About

urlpatterns = [
    path('about-us/', About.as_view(), name='about-us'),

    path('admin/', admin.site.urls),

    path('', include('userprofile.urls')),

    path('', include('posts.urls')),

    path('', frontpage, name='front-page'),

    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

from posts.forms import UserLoginForm

urlpatterns = [
    #Ingreso
    path('sign-up/', views.signup, name='sign-up'),
    path('log-in/', auth_views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=UserLoginForm), name='log-in'),
    path('log-out/', auth_views.LogoutView.as_view(), name='log-out'),

    #Mi cuenta
    path('my-account/', views.myaccount, name='my-account'),
    path('my-account/edit-profile/<int:pk>/', views.editar_perfil, name='edit-profile'),
    path('my-account/edit-account/', views.editar_cuenta, name='edit-account'),
    path('my-account/change-password/', views.cambiar_contrasenya, name='change-password'),
    path('my-account/change-subscription/', views.cambiar_sub, name='change-subscription'),
    path('a-vender/', views.to_vendor, name='a-vender'),

    #Mis publicaciones
    path('my-posts/', views.my_posts, name='my-posts'),
    path('my-posts/add-product/', views.add_product, name='add_product'),
    path('my-posts/edit-product/<int:pk>/', views.edit_product, name='edit_product'),
    path('my-posts/delete-product/<int:pk>/', views.delete_product, name='delete_product'),

    #Publicaciones de vendedores
    path('vendors/<int:pk>/', views.vendor_detail, name='vendor-detail'),
    path('vendor-profile/<int:pk>/', views.vendor_profile, name='profile'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from django_ckeditor_5.fields import CKEditor5Field

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="userprofile", on_delete=models.CASCADE)
    numero = models.CharField(max_length=10)
    edad = models.PositiveSmallIntegerField(null=False, blank=False, default=18)
    about_me = CKEditor5Field(null=True, blank=True, max_length=150)
    instagram = models.CharField(null=True, max_length=15, blank=True)
    universidad = models.CharField(choices={
        'EAFIT':'Universidad EAFIT',
        'UDEA':'Universidad de Antioquia',
        'CES':'Universidad CES',
        'UPB':'Universidad Pontificia Bolivariana',
        'ANDES':'Universidad de los Andes',
    }, default='EAFIT', max_length=5)
    imagen = models.ImageField(upload_to='uploads/userprofile/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    saved_posts = [] #new list variable to store the ids of posts
    
    
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.user.username
    
    def save_post(self, post_id):
        self.saved_posts.append(post_id)
    
    def delete_post(self, post_id):
        self.saved_posts.remove(post_id)

    def len_saved_post(self):
        return len(self.saved_posts)
    
    def get_display_number(self):
        return "https://web.whatsapp.com/send/?phone=57"+self.numero+"/"
    
    def get_display_instagram(self):
        return "https://www.instagram.com/"+self.instagram+"/"
    
    def get_display_university(self):
        return self.universidad
    
    def am_vendor(self):
        return self.user.groups.filter(name='Emprendedores').exists()
    
    def get_posts(self):
        return self.product_set.objects.all()
    
    def get_comments(self):
        return self.comentario_set.objects.all()
    
def create_profile(sender, instance, created, **kwargs):
     if created:
        user_profile = UserProfile(user=instance)
        user_profile.save()

post_save.connect(create_profile, sender=User)

userprofile/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group, User
from django.contrib.auth import login
from django.contrib import messages

from django.utils.text import slugify

from django.db.models import Avg

from posts.models import Product

from .models import UserProfile

from posts.forms import ProductForm, UserForm, AccountForm, SignupForm
from reviews.models import ReviewDetails, Reseña

def es_vendedor(request):
    return request.groups.filter(name='Emprendedores').exists()

@login_required(login_url='log-in')
def cambiar_sub(request):
    if not es_vendedor(request.user):
        user = request.user
        return render (request, 'userprofile/change_sub.html', { 'user':user })
    else:
        return redirect('my-account')
    
@login_required(login_url='log-in')
def to_vendor(request):
    if not es_vendedor(request.user):
        user = request.user
        vendors = Group.objects.get(name='Emprendedores')
        vendors.user_set.add(user)

    return redirect('my-account')

def vendor_detail(request, pk):
    user = User.objects.get(pk=pk)
    products = user.products.filter(status=Product.ACTIVO)

    return render(request, 'userprofile/vendor_detail.html', {'user':user, 'products':products})

@login_required(login_url='log-in')
@user_passes_test(es_vendedor, login_url='change-subscription')
def my_posts(request):
    products = request.user.products.exclude(status=Product.ELIMINADO)

    return render(request, 'userprofile/my_posts.html', {'products':products})

@login_required(login_url='log-in')
@user_passes_test(es_vendedor)
def add_product(request):
    if request.method=='POST':
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            title = request.POST.get('title')

            product = form.save(commit=False)
            product.user = request.user
            product.slug = slugify(title)
            product.save()

            form.save_m2m()

            reviews = ReviewDetails.objects.create(product=product, promedio=0.0, comentarios=0)

            reviews.save()

            messages.success(request, 'Publicación creada')

            return redirect('my-posts')
    else:
        form = ProductForm()

    return render(request, 'userprofile/product_form.html', {'title':'Añadir publicación', 'form':form})

@login_required(login_url='log-in')
@user_passes_test(es_vendedor)
def edit_product(request, pk):
    product = Product.objects.filter(user=request.user).get(pk=pk)

    if request.method=='POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()

            messages.success(request, 'Los cambios se han guardado correctamente')

            return redirect('my-posts')
    else:
        form = ProductForm(instance=product)

    return render(request, 'userprofile/product_form.html', {'title':'Editar publicación', 'form':form})

@login_required(login_url='log-in')
@user_passes_test(es_vendedor)
def delete_product(request, pk):
    product = Product.objects.filter(user=request.user).get(pk=pk)
    product.status = Product.ELIMINADO
    product.save()
    
    messages.success(request, 'La publicación se ha eliminado correctamente')

    return redirect('my-posts')

@login_required(login_url='log-in')
def myaccount(request):
    return render(request, 'userprofile/myaccount.html')

@login_required(login_url='log-in')
def editar_perfil(request, pk):
    user = UserProfile.objects.filter(user=request.user).get(pk=pk)

    if request.method=='POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Los cambios se han guardado correctamente')

            return redirect('my-account')
    else:
        form = UserForm(instance=user)

    return render(request, 'userprofile/profile_form.html', {'title':'Editar perfil', 'form':form})

@login_required(login_url='log-in')
def editar_cuenta(request):
    if request.method=='POST':
        form = AccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Los cambios se han guardado correctamente')

            return redirect('my-account')
    else:
        form = AccountForm(instance=request.user)

    return render(request, 'userprofile/profile_form.html', {'title':'Editar cuenta', 'form':form})

@login_required(login_url='log-in')
def cambiar_contrasenya(request):
    if request.method=='POST':
        form = PasswordChangeForm(request.POST)
    
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Los cambios se han guardado correctamente')

            return redirect('my-account')
        else:
            messages.warning(request, 'Ingrese los datos correctamente')
    else:
        form = PasswordChangeForm(request.POST)
    
    return render(request, 'userprofile/profile_form.html', { 'title':'Cambiar Contraseña', 'form':form })


def vendor_profile(request, pk):
    user = User.objects.get(pk=pk)

    return render(request, 'userprofile/vendor_profile.html', {'user':user})

def signup(request):
    if request.method=='POST':
        form = SignupForm(request.POST)
    
        if form.is_valid():
            user = form.save()

            login(request, user)

            userprofile = UserProfile.objects.create(user=user)

            return redirect('front-page')
    else:
        form = SignupForm()
    
    return render(request, 'userprofile/signup.html', { 'form':form })

userprofile/templates/userprofile/change_sub.html
{% extends 'core/base.html' %}

{% block title %}
  Ser vendedor
{% endblock %}

{% block content %}

<h1 class="text-3xl mb-5">CAMBIATE A EMPRENDEDOR</h1>

<div class="flex items-center justify-center">
  <div class="lg:w-1/3 px-6 py-4 transition-colors duration-200 transform bg-gray-700 rounded-lg dark:bg-gray-600">
    <p class="text-lg font-medium text-gray-100">Emprendedor</p>
    <h4 class="mt-2 text-4xl font-semibold text-gray-100">$9,990 pesos<span class="text-base font-normal text-gray-400">/ mensual</span></h4>
    <p class="mt-4 text-gray-300">Para aquellos que quieren hacer conocer su negocio</p>
  
    <div class="mt-8 space-y-8">
        <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
  
            <span class="mx-4 text-gray-300">All limited links</span>
        </div>
  
        <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
  
            <span class="mx-4 text-gray-300">Own analytics platform</span>
        </div>
  
        <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
  
            <span class="mx-4 text-gray-300">Chat support</span>
        </div>
  
        <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
  
            <span class="mx-4 text-gray-300">Optimize hashtags</span>
        </div>
  
        <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
  
            <span class="mx-4 text-gray-300">Unlimited users</span>
        </div>
    </div>
  
    <form id="change-form" method="POST">
      {% csrf_token %}
    <button type="submit" class="w-full px-4 py-2 mt-10 font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:bg-blue-600">
        Ser emprendedor
    </button>
    </form>
  </div>
</div>

<script>
  $(document).on('submit', '#change-form', function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:"{% url 'a-vender' %}",
      data:{
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(response){
        console.log(response);
        alert("Ya eres un emprendedor");
      }
    });
  });  
</script>

{% endblock content %}

userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %}

{% block title %}
  Ingreso
{% endblock %}

{% block content %}
  <style>
    .login_img_section {
      background: linear-gradient(rgba(2, 2, 2, 0.7), rgba(0, 0, 0, 0.7)), url(https://miro.medium.com/v2/resize:fit:720/format:webp/1*kD63_v2-qaX8yzaXt1Zbbw.jpeg) center center;
    }
  </style>
  <div class="h-screen flex overflow:hidden">
    <div class="hidden lg:flex w-full lg:w-1/2 login_img_section justify-around items-center">
      <div class="bg-black opacity-20 inset-0 z-0"></div>
      <div class="w-full mx-auto px-20 flex-col items-center space-y-6">
        <h1 class="text-white font-bold text-4xl font-sans">UniMarket</h1>
        <p class="text-white mt-1">Plataforma de compra y venta en universidades</p>
        <div class="flex justify-center lg:justify-start mt-6">
          <a href="/sign-up/" class="hover:bg-gray-700 hover:text-gray-400 hover:-translate-y-1 transition-all duration-500 bg-white text-gray-800 mt-4 px-4 py-2 rounded-2xl font-bold mb-2">Empezar</a>
        </div>
      </div>
    </div>
    
    <div class="flex w-full lg:w-1/2 justify-center items-center bg-gray-100 space-y-8">
      <div class="w-full px-8 md:px-32 lg:px-24">
        
        {% include 'userprofile/partials/login.html' %}

        <div class="flex justify-between mt-4">
          <span class="text-sm ml-2 hover:text-gray-500 cursor-pointer hover:-translate-y-1 duration-200 transition-all">¿Olvidaste tu contraseña?</span>

          <a href="{% url 'sign-up' %}" class="text-sm ml-2 hover:text-gray-500 cursor-pointer hover:-translate-y-1 duration-200 transition-all">¿No tienes una cuenta aún?</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}

{% block title %}
  Mi Cuenta
{% endblock %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="mt-4 text-tail-800 font-bold">{{ message }}</div>
    {% endfor %}
  {% endif %}

  <div class="mx-4 my-2">
    <h1 class="text-3xl mb-2">Mi cuenta</h1>

    <div>
      <h2 class="text-xl my-4">Usuario: {{ user.username }}</h2>
    {% if user.get_full_name %}
      <h2 class="text-xl my-4">Nombre: {{ user.get_full_name }}</h2>
    {% endif %}
  
    <h2 class="text-xl my-4">
      Correo:{% if user.email %}
        {{ user.email }}
      {% else %}
        No tiene
      {% endif %}
    </h2>
    </div>
  
    <div class="flex items-center mt-4">
      <a href="{% url 'edit-account' %}" class="inline-block mr-4 p-3 bg-gray-600 text-white hover:bg-gray-800 active:bg-gray-900 rounded-lg">Editar cuenta</a>

      <a href="{% url 'change-password' %}" class="inline-block mr-4 p-3 bg-gray-600 text-white hover:bg-gray-800 active:bg-gray-900 rounded-lg">Cambiar contraseña</a>
    </div>

  <hr class="border border-gray-600 my-5">

  <h1 class="text-3xl mb-2">Información de mi perfil</h1>

  <h2 class="text-xl my-4">
    Imagen:{% if user.userprofile.imagen %}
      <img src="{{ user.userprofile.imagen.url }}" alt="Imagen de {{ user.username }}" class="w-44 h-44 rounded-full object-cover" />
    {% else %}
      No tiene
    {% endif %}
  </h2>

  <h2 class="text-xl my-4">Numero: +57 {{ user.userprofile.numero }}</h2>

  <h2 class="text-xl my-4">
    Instagram:{% if user.userprofile.instagram %}
      @{{ user.userprofile.instagram }}
    {% else %}
      No tiene
    {% endif %}
  </h2>

  <h2 class="text-xl my-4">Edad: {{user.userprofile.edad}}</h2>

  {% if user.userprofile.about_me %}
  <h2 class="text-xl my-4">Sobre mi: <br> {{user.userprofile.about_me}}</h2>
  {% endif %}

  <h2 class="text-xl my-4">Institución universitaria: {{ user.userprofile.get_universidad_display }}</h2>

  <div class="flex items-center mt-6">
    <a href="{% url 'edit-profile' user.userprofile.id %}" class="inline-block p-3 bg-gray-600 text-white hover:bg-gray-800 active:bg-gray-900 rounded-lg">Editar perfil</a>
  </div>
  </div>
{% endblock %}

userprofile/templates/userprofile/product_form.html
{% extends 'core/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
  <div class="flex items-center justify-between">
    <h1 class="text-xl mb-2">{{ title }}</h1>
  </div>

  <form action="." method="post" enctype="multipart/form-data" class="space-y-5">
    {% csrf_token %}

    {{ form.as_p }}

    <button class="py-3 px-6 bg-gray-500 text-white hover:bg-gray-700 active:bg-gray-900 rounded-lg" type="submit">Guardar publicación</button>
  </form>
{% endblock %}

userprofile/templates/userprofile/vendor_profile.html
{% extends 'core/base.html' %}

{% block title %}
  {% firstof user.get_full_name user.username %}
{% endblock %}

{% block content %}
  <div class="p-16">
    <div class="p-8 bg-gray-200 shadow mt-8">
      <div class="grid grid-cols-1 md:grid-cols-3">
        <div class="grid grid-cols-3 text-center order-last md:order-first mt-20 md:mt-0">
          <div>
            <p class="font-bold text-gray-700 text-xl">{{ user.products.count }}</p>
            <p class="text-gray-600">Publicaciones</p>
          </div>
          <div>
            <p class="font-bold text-gray-700 text-xl">{{ user.comment_user.count }}</p>
            <p class="text-gray-600">Reseñas hechas</p>
          </div>
          <div>
            <p class="font-bold text-gray-700 text-xl">89</p>
            <p class="text-gray-600">Comments</p>
          </div>
        </div>
        <div class="relative">
          <div class="rounded-full absolute -mt-24 flex items-center justify-center">
            {% if user.userprofile.imagen %}
                    <img src="{{ user.userprofile.imagen.url }}"
                        alt="Imagen de {{ user.username }}"
                        class="w-64 h-64 rounded-full object-cover mr-2" />
                    {% else %}
                    <img src="/media/uploads/userprofile/No%20Photo.jpg"
                        alt="Imagen de {{ user.username }}"
                        class="w-64 h-64 rounded-full object-cover mr-2" />
                    {% endif %}
          </div>
        </div>

        <div class="space-x-8 flex justify-between mt-32 md:mt-0 md:justify-center">
          <a class="transition transform hover:-translate-y-1 delay-100 duration-500" href="{% url 'vendor-detail' user.id %}">
            <button class="text-white py-2 px-4 uppercase rounded bg-gray-400 hover:bg-gray-500 shadow hover:shadow-lg font-medium duration-500">
                Publicaciones
              </button>
          </a>
        </div>
      </div>

      <div class="mt-20 text-center border-b pb-12">
        <h1 class="text-4xl font-medium text-gray-700">{% firstof user.get_full_name user.username %}, <span class="font-light text-gray-500">{{ user.userprofile.edad }} años</span></h1>
        <p class="font-light text-gray-600 mt-3">{{ user.userprofile.get_universidad_display }}</p>

        <div class="flex items-center justify-center mt-2">
          <div class="flex items-center justify-between">
            <a title="WhatsApp" class="text-gray-700 mx-3" href="{{ user.userprofile.get_display_number }}" target="_blank">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7 hover:text-green-600 active:text-green-800 delay-50 duration-700" fill="currentColor" viewBox="0 0 24 24">
                <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z" />
              </svg>
            </a>

            {% if user.userprofile.instagram %}
              <a title="Instagram" class="delay-50 duration-700 text-gray-700 hover:text-pink-600 active:text-pink-800" href="{{ user.userprofile.get_display_instagram }}" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="h-8">
                  <path fill="currentColor" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path>
                </svg>
              </a>
            {% endif %}
          </div>
        </div>

        <p class="mt-8 text-gray-500">Solution Manager - Creative Tim Officer</p>
        <p class="mt-2 text-gray-500">University of Computer Science</p>
      </div>

      <div class="mt-12 flex flex-col justify-center">
        <p class="text-gray-600 text-center font-light lg:px-16">
          {% if user.userprofile.about_me %}
          {{ user.userprofile.about_me }}
          {% else %}
          Sin descripción
          {% endif %}
        </p>
        <button class="text-gray-500 py-2 px-4 mt-4 hover:tracking-widest delay-100 duration-500">
          <b>Mostrar más</b>
        </button>
      </div>
    </div>
  </div>
{% endblock %}